# コード品質チェック用ワークフロー
name: Lint & Format Check
on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Node.jsをセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: 依存パッケージをインストール
        run: cd frontend && npm install

      - name: ESLintでコードチェック（警告許可）
        run: cd frontend && npx eslint . --ext .ts,.tsx --max-warnings 10

      - name: Prettierで自動整形チェック
        run: cd frontend && npx prettier --check . || true

  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Ruffをインストール
        run: pip install ruff

      - name: Ruffでコードチェック
        run: ruff check backend/ --fix

      - name: Ruffでフォーマットチェック
        run: ruff format backend/ --check
